---
title: "Discussion, Week 1"
subtitle: "Fracking"
editor_options: 
  chunk_output_type: console
---

## Setup
```{r}
# load packages ----
library(tidyverse)
library(janitor)

# import data ----
fracking <- read_csv(here::here("week1", "data", "fracking-20240110.csv"))
```

## Wrangle data
```{r}
fracking_clean <- fracking |> 
  
  # clean column names ----
janitor::clean_names() |> 
  
  # clean up dates ----
mutate(job_start_date = str_remove(job_start_date, " AM")) |> 
  mutate(datetime_start = mdy_hms(job_start_date)) |> 
  mutate(year = year(datetime_start)) |> 
  
  # select relevant cols ----
select(datetime_start, year, state_name, county_name, well_name, total_base_water_volume) |> 
  
  # convert state_name from string to factor ----
mutate(state_name = as.factor(state_name)) |> 
  
  # filter out non-state names ----
filter(!state_name %in% c("Beaver", "Beckham", "Harper", "Hemphill", "Midland", "Red River", "Roosevelt", "Rusk", "State", "WARD")) |> 
  
  # rename state_name to something shorter for typing out when using case_when (not necessary) ----
rename(sn = state_name) |> 
  
  # make all words title case ----
mutate(sn = str_to_title(sn)) |> 
  
  # fix misspelled state names ----
mutate(sn = case_when(
  sn == "Colordao" ~ "Colorado",
  sn == "Loiusiana" ~ "Louisiana",
  sn == "Louisianna" ~ "Louisiana",
  sn == "Lousiana" ~ "Louisiana",
  sn == "New Mexcio" ~ "New Mexico",
  sn == "Norh Dakota" ~ "North Dakota",
  sn == "Norht Dakota" ~ "North Dakota",
  sn == "North  Dakota" ~ "North Dakota",
  sn == "North Dakata" ~ "North Dakota",
  sn == "North Dakotta" ~ "North Dakota",
  sn == "Noth Dakota" ~ "North Dakota",
  sn == "Pennslvania" ~ "Pennsylvania",
  sn == "Pennsylavania" ~ "Pennsylvania",
  sn == "Pennsylvanya" ~ "Pennsylvania",
  sn == "Penssylvania" ~ "Pennsylvania",
  sn == "Texasa" ~ "Texas",
  sn == "Texs" ~ "Texas", 
  sn == "West Viginia" ~ "West Virginia",
  sn == "Wyominng" ~ "Wyoming", 
  TRUE ~ sn # copy over rest of state names from as-is
)) |> 
  
  # remove rows that have a ? mark ----
filter(!str_detect(sn, "\\?")) |> # `?` is a special chr; escape with `\\` prefix
  
  # make all works uppercase (so that we can covert abb to state names) ----
mutate(sn = str_to_upper(sn)) |> 
  
  # mutate abbs to full state names ----
mutate(sn = ifelse(test = str_length(sn) == 2, 
                   yes = usdata::abbr2state(sn),
                   no = sn)) |> 
  
  # make all words title case again ----
mutate(sn = str_to_title(sn)) |> 
  
  # create a column of just state abbs ----
mutate(state_abb = usdata::state2abbr(sn)) |> 
  
  # rename sn to state_name again for clarity ----
rename(state_name = sn, total_base_water_volume_gal = total_base_water_volume) |> 
  
  # move state_abb col after state_name col ----
relocate(state_abb, .after = state_name) |> 
  
  # remove obs that don't have a measurement for total_base_water_volume (NA) ----
drop_na(total_base_water_volume_gal)
```

